# Generated by Django 3.2.23 on 2023-11-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Arcade', 'Arcade'), ('Beat Em Up', 'Beat Em Up'), ('Ego-Shooter', 'Ego-Shooter'), ("Jump 'n' Run", "Jump 'n' Run"), ('Racing', 'Racing'), ('RPG', 'RPG'), ('Simulation', 'Simulation'), ('Sports', 'Sports'), ('Strategy', 'Strategy'), ('Puzzle', 'Puzzle'), ('Horror', 'Horror')], max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='platform',
            field=models.CharField(blank=True, choices=[('Dreamcast', 'Dreamcast'), ('Gameboy', 'Gameboy'), ('Gameboy Color', 'Gameboy Color'), ('NES', 'NES'), ('N64', 'N64'), ('PC', 'PC'), ('PlayStation', 'PlayStation'), ('PlayStation 2', 'PlayStation 2'), ('Sega Genesis', 'Sega Genesis'), ('SNES', 'SNES'), ('XBOX', 'XBOX')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(choices=[(0, '0.0 Stars'), (0.5, '0.5 Stars'), (1, '1.0 Stars'), (1.5, '1.5 Stars'), (2, '2.0 Stars'), (2.5, '2.5 Stars'), (3, '3.0 Stars'), (3.5, '3.5 Stars'), (4, '4.0 Stars'), (4.5, '4.5 Stars'), (5, '5.0 Stars')], decimal_places=1, default=0, max_digits=2),
        ),
    ]
